Testing for protection rule
RodTol/Crossway pull request #4
Opened 2022-11-08 18:01 UTC by RodTol

I modified the Readme and now I ask for a merge who should be forced

2022-11-08 18:03 UTC, RodTol reviewed
I approve the changes

2022-11-09 08:47 UTC, giuliabernardi1 requested changes
bello ma no

2022-11-09 08:48 UTC, RodTol reviewed
Ti prego

2022-11-09 08:49 UTC, giuliabernardi1 approved these changes
ok

2022-11-09 08:50 UTC, merged